### ISSUE TITLE
train.py - "Could not recognize scene type!"

### ISSUE THREAD

**Issue by Blizaine** [camenduru/gaussian-splatting-colab#3]
Hello,
Thanks for all the work you do on this project.  I'm having an issue with training my own images.  I initially was using Google Colab tied back to my Windows/Docker (and 4090), but then recently went ahead and tried the local option.  I extracted about 450 images from drone footage and ran it through COLMAP via convert.py.  

In both colab and local, I get an error: "Could not recognize scene type!" when I run train.py.  I'm pointing it to the directory that has folders for images, sparse, distorted, input and two .sh files, that were a result of convert.py.  Any ideas?  

```
(gaussian_splatting) C:\Users\bliza\conda\gaussian-splatting>python train.py -s /data/DroneFinal
Optimizing
Output folder: ./output/615ddd4f-b [28/08 08:54:59]
Tensorboard not available: not logging progress [28/08 08:54:59]
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Users\bliza\conda\gaussian-splatting\scene\__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```

**Comment by Blizaine** [comment]
Sorry, I meant to put this in the main branch.  Closing.
