### ISSUE TITLE
Notebook is broken

### ISSUE THREAD

**Issue by fasteinke** [camenduru/gaussian-splatting-colab#7]
Was working fine until today ...

Throws this error,

Traceback (most recent call last):
  File "/content/gaussian-splatting/train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/content/gaussian-splatting/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/usr/local/lib/python3.10/dist-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by ghost** [comment]
Following [this answer](https://stackoverflow.com/questions/64683003/importerror-libcudart-so-10-1-cannot-open-shared-object-file-no-such-file-or) I solved with `apt install nvidia-cuda-toolkit`

**Comment by fasteinke** [comment]
Didn't try it - see the other method, that worked for me, https://github.com/camenduru/gaussian-splatting-colab/issues/8 ... thanks!

**Comment by camenduru** [comment]
thanks ❤
